bin/qBitInjectTrackers: improvements to script

diff --git a/bin/qBitInjectTrackers b/bin/qBitInjectTrackers
--- a/bin/qBitInjectTrackers
+++ b/bin/qBitInjectTrackers
@@ -11,11 +11,11 @@ ignore_private=false
 
 # Configure here your trackers list
 declare -a live_trackers_list_urls=(
-	"https://newtrackon.com/api/stable"
-	"https://trackerslist.com/best.txt"
-	"https://trackerslist.com/http.txt"
-	"https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt"
-	)
+  "https://newtrackon.com/api/stable"
+  "https://trackerslist.com/best.txt"
+  "https://trackerslist.com/http.txt"
+  "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt"
+  )
 ########## CONFIGURATIONS ##########
 
 jq_executable="$(command -v jq)"
@@ -26,28 +26,28 @@ applytheforce=0
 all_torrent=0
 
 if [[ -z $jq_executable ]]; then
-	echo -e "\n\e[0;91;1mFail on jq. Aborting.\n\e[0m"
-	echo "You can find it here: https://stedolan.github.io/jq/"
-	echo "Or you can install it with -> sudo apt install jq"
-	exit 1
+  echo -e "\n\e[0;91;1mFail on jq. Aborting.\n\e[0m"
+  echo "You can find it here: https://stedolan.github.io/jq/"
+  echo "Or you can install it with -> sudo apt install jq"
+  exit 1
 fi
 
 if [[ -z $curl_executable ]]; then
-	echo -e "\n\e[0;91;1mFail on curl. Aborting.\n\e[0m"
-	echo "You can install it with -> sudo apt install curl"
-	exit 2
+  echo -e "\n\e[0;91;1mFail on curl. Aborting.\n\e[0m"
+  echo "You can install it with -> sudo apt install curl"
+  exit 2
 fi
 
 ########## FUNCTIONS ##########
 generate_trackers_list () {
-	for j in "${live_trackers_list_urls[@]}"; do
-		tmp_trackers_list+=$($curl_executable -sS $j)
-		tmp_trackers_list+=$'\n'
-	done
+  for j in "${live_trackers_list_urls[@]}"; do
+    tmp_trackers_list+=$($curl_executable -sS $j)
+    tmp_trackers_list+=$'\n'
+  done
 
-	trackers_list=$(echo "$tmp_trackers_list" | awk '{for (i=1;i<=NF;i++) if (!a[$i]++) printf("%s%s",$i,FS)}{printf("\n")}' | xargs | tr ' ' '\n')
-	if [[ $? -ne 0 ]]; then
-		echo "I can't download the list, I'll use a static one"
+  trackers_list=$(echo "$tmp_trackers_list" | awk '{for (i=1;i<=NF;i++) if (!a[$i]++) printf("%s%s",$i,FS)}{printf("\n")}' | xargs | tr ' ' '\n')
+  if [[ $? -ne 0 ]]; then
+    echo "I can't download the list, I'll use a static one"
 cat >"${trackers_list}" <<'EOL'
 udp://tracker.coppersurfer.tk:6969/announce
 http://tracker.internetwarriors.net:1337/announce
@@ -109,240 +109,243 @@ http://retracker.mgts.by:80/announce
 http://peersteers.org:80/announce
 http://fxtt.ru:80/announce
 EOL
-	fi
-	number_of_trackers_in_list=$(echo "$trackers_list" | wc -l)
+  fi
+  number_of_trackers_in_list=$(echo "$trackers_list" | wc -l)
+  echo -e "\e[0;32;1mTrackers:\e[0m"
+  echo "$trackers_list"
 }
 
 inject_trackers () {
-	start=1
-	while read tracker; do
-		if [ -n "$tracker" ]; then
-			echo -ne "\e[0;36;1m$start/$number_of_trackers_in_list - Adding tracker $tracker\e[0;36m"
-			$curl_executable --silent --fail --show-error \
-				-d "hash=${1}&urls=${tracker}" \
-				--request POST "${qbt_host}:${qbt_port}/api/v2/torrents/addTrackers"
-
-
-
-			if [ $? -eq 0 ]; then
-				echo -e " -> \e[32mSuccess! "
-			else
-				echo -e " - \e[31m< Failed > "
-			fi
-		fi
-		start=$((start+1))
-	done <<< "$trackers_list"
-	echo "Done!"
+  start=1
+  local urls=""
+  while read tracker; do
+    if [ -n "$tracker" ]; then
+      urls="$tracker%0A%0A$urls"
+    fi
+    start=$((start+1))
+  done <<< "$trackers_list"
+  echo -ne "\e[0;36;1mAdding $number_of_trackers_in_list trackers...\e[0;36m"
+  $curl_executable --silent --fail --show-error \
+    -d "hash=${1}&urls=${urls}" \
+    --request POST "${qbt_host}:${qbt_port}/api/v2/torrents/addTrackers"
+  local rc=$?
+  if [ $rc -eq 0 ]; then
+    echo -e " \e[32mSuccess!\e[0m"
+  else
+    echo -e " \e[31m< Failed >\e[0m"
+    exit $rc
+  fi
+  echo "Done!"
 }
 
 get_torrent_list () {
-	torrent_list=$($curl_executable --silent --fail --show-error \
-		--request GET "${qbt_host}:${qbt_port}/api/v2/torrents/info")
+  torrent_list=$($curl_executable --silent --fail --show-error \
+    --request GET "${qbt_host}:${qbt_port}/api/v2/torrents/info")
 }
 
 hash_check() {
-	case $1 in
-		( *[!0-9A-Fa-f]* | "" ) return 1 ;;
-		( * )
-			case ${#1} in
-				( 32 | 40 ) return 0 ;;
-				( * )       return 1 ;;
-			esac
-	esac
+  case $1 in
+    ( *[!0-9A-Fa-f]* | "" ) return 1 ;;
+    ( * )
+      case ${#1} in
+        ( 32 | 40 ) return 0 ;;
+        ( * )       return 1 ;;
+      esac
+  esac
 }
 
 wait() {
-	w=$1
-	echo "I'll wait ${w}s to be sure ..."
-	while [ $w -gt 0 ]; do
-		echo -ne "$w\033[0K\r"
-		sleep 1
-		w=$((w-1))
-	done
+  w=$1
+  echo "I'll wait ${w}s to be sure ..."
+  while [ $w -gt 0 ]; do
+    echo -ne "$w\033[0K\r"
+    sleep 1
+    w=$((w-1))
+  done
 }
 ########## FUNCTIONS ##########
 
 if [ -t 1 ] ; then
-	if [[ ! $@ =~ ^\-.+ ]]; then
-		echo "Arguments must be passed with - in front, like -n foo. Check instructions"
-		echo ""
-		$0 -h
-		exit
-	fi
+  if [[ ! $@ =~ ^\-.+ ]]; then
+    echo "Arguments must be passed with - in front, like -n foo. Check instructions"
+    echo ""
+    $0 -h
+    exit
+  fi
 
-	[ $# -eq 0 ] && $0 -h
+  [ $# -eq 0 ] && $0 -h
 
-	if [ $# -eq 1 ] && [ $1 == "-f" ]; then
-		echo "Don't use only -f, you need to specify also the torrent!"
-		exit
-	fi
+  if [ $# -eq 1 ] && [ $1 == "-f" ]; then
+    echo "Don't use only -f, you need to specify also the torrent!"
+    exit
+  fi
 
-	while getopts ":aflhn:" opt; do
-		case ${opt} in
-			a ) # If used inject trackers to all torrent.
-				all_torrent=1
-				;;
-			f ) # If used force the injection also in private trackers.
-				applytheforce=1
-				;;
-			l ) # Print the list of the torrent where you can inject trackers.
-				get_torrent_list
-				echo -e "\e[0;32;1mCurrent torrents:\e[0;32m"
-				echo "$torrent_list" | $jq_executable --raw-output '.[] .name'
-				exit
-				;;
-			n ) # Specify the name of the torrent example -n foo or -n "foo bar", multiple -n can be used.
-				tor_arg_names+=("$OPTARG")
-				;;
-			: )
-				echo "Invalid option: -${OPTARG} requires an argument" 1>&2
-				exit 0
-				;;
-			\? )
-				echo "Unknow option: -${OPTARG}" 1>&2
-				exit 1
-				;;
-			h | * ) # Display help.
-				echo "Usage:"
-				echo "$0 -a	Inject trackers to all torrent in qBittorrent, this not require any extra information"
-				echo "$0 -f	Force the injection of the trackers inside the private torrent too, this not require any extra information"
-				echo "$0 -l	Print the list of the torrent where you can inject trackers, this not require any extra information"
-				echo "$0 -n	Specify the torrent name or part of it, for example -n foo or -n 'foo bar'"
-				echo "$0 -h	Display this help"
-				echo "NOTE:"
-				echo "It's possible to specify more than -n in one single command"
-				echo "Just remember that if you set -a in useless to add any extra -n, but -f can always be used"
-				exit 2
-				;;
-		esac
-	done
-	shift $((OPTIND -1))
+  while getopts ":aflhn:" opt; do
+    case ${opt} in
+      a ) # If used inject trackers to all torrent.
+        all_torrent=1
+        ;;
+      f ) # If used force the injection also in private trackers.
+        applytheforce=1
+        ;;
+      l ) # Print the list of the torrent where you can inject trackers.
+        get_torrent_list
+        echo -e "\e[0;32;1mCurrent torrents:\e[0;32m"
+        echo "$torrent_list" | $jq_executable --raw-output '.[] .name'
+        exit
+        ;;
+      n ) # Specify the name of the torrent example -n foo or -n "foo bar", multiple -n can be used.
+        tor_arg_names+=("$OPTARG")
+        ;;
+      : )
+        echo "Invalid option: -${OPTARG} requires an argument" 1>&2
+        exit 0
+        ;;
+      \? )
+        echo "Unknow option: -${OPTARG}" 1>&2
+        exit 1
+        ;;
+      h | * ) # Display help.
+        echo "Usage:"
+        echo "$0 -a  Inject trackers to all torrent in qBittorrent, this not require any extra information"
+        echo "$0 -f  Force the injection of the trackers inside the private torrent too, this not require any extra information"
+        echo "$0 -l  Print the list of the torrent where you can inject trackers, this not require any extra information"
+        echo "$0 -n  Specify the torrent name or part of it, for example -n foo or -n 'foo bar'"
+        echo "$0 -h  Display this help"
+        echo "NOTE:"
+        echo "It's possible to specify more than -n in one single command"
+        echo "Just remember that if you set -a in useless to add any extra -n, but -f can always be used"
+        exit 2
+        ;;
+    esac
+  done
+  shift $((OPTIND -1))
 else
-	if [[ -n "${sonarr_download_id}" ]] || [[ -n "${radarr_download_id}" ]] || [[ -n "${lidarr_download_id}" ]] || [[ -n "${readarr_download_id}" ]]; then
-		#wait 5
-		if [[ -n "${sonarr_download_id}" ]]; then
-			echo "Sonarr variable found -> $sonarr_download_id"
-			hash=$(echo "$sonarr_download_id" | awk '{print tolower($0)}')
-		fi
+  if [[ -n "${sonarr_download_id}" ]] || [[ -n "${radarr_download_id}" ]] || [[ -n "${lidarr_download_id}" ]] || [[ -n "${readarr_download_id}" ]]; then
+    #wait 5
+    if [[ -n "${sonarr_download_id}" ]]; then
+      echo "Sonarr variable found -> $sonarr_download_id"
+      hash=$(echo "$sonarr_download_id" | awk '{print tolower($0)}')
+    fi
 
-		if [[ -n "${radarr_download_id}" ]]; then
-			echo "Radarr variable found -> $radarr_download_id"
-			hash=$(echo "$radarr_download_id" | awk '{print tolower($0)}')
-		fi
+    if [[ -n "${radarr_download_id}" ]]; then
+      echo "Radarr variable found -> $radarr_download_id"
+      hash=$(echo "$radarr_download_id" | awk '{print tolower($0)}')
+    fi
 
-		if [[ -n "${lidarr_download_id}" ]]; then
-			echo "Lidarr variable found -> $lidarr_download_id"
-			hash=$(echo "$lidarr_download_id" | awk '{print tolower($0)}')
-		fi
+    if [[ -n "${lidarr_download_id}" ]]; then
+      echo "Lidarr variable found -> $lidarr_download_id"
+      hash=$(echo "$lidarr_download_id" | awk '{print tolower($0)}')
+    fi
 
-		if [[ -n "${readarr_download_id}" ]]; then
-			echo "Readarr variable found -> $readarr_download_id"
-			hash=$(echo "$readarr_download_id" | awk '{print tolower($0)}')
-		fi
+    if [[ -n "${readarr_download_id}" ]]; then
+      echo "Readarr variable found -> $readarr_download_id"
+      hash=$(echo "$readarr_download_id" | awk '{print tolower($0)}')
+    fi
 
-		hash_check "${hash}"
-		if [[ $? -ne 0 ]]; then
-			echo "The download is not for a torrent client, I'll exit"
-			exit 3
-		fi
-		auto_tor_grab="1"
-	fi
+    hash_check "${hash}"
+    if [[ $? -ne 0 ]]; then
+      echo "The download is not for a torrent client, I'll exit"
+      exit 3
+    fi
+    auto_tor_grab="1"
+  fi
 
-	if [[ $sonarr_eventtype == "Test" ]] || [[ $radarr_eventtype == "Test" ]] || [[ $lidarr_eventtype == "Test" ]] || [[ $readarr_eventtype == "Test" ]]; then
-		echo "Test in progress..."
-		test_in_progress=1
-	fi
+  if [[ $sonarr_eventtype == "Test" ]] || [[ $radarr_eventtype == "Test" ]] || [[ $lidarr_eventtype == "Test" ]] || [[ $readarr_eventtype == "Test" ]]; then
+    echo "Test in progress..."
+    test_in_progress=1
+  fi
 fi
 
 for i in "${tor_arg_names[@]}"; do
-	if [[ -z "${i// }" ]]; then
-		echo "one or more argument for -n not valid, try again"
-		exit
-	fi
+  if [[ -z "${i// }" ]]; then
+    echo "one or more argument for -n not valid, try again"
+    exit
+  fi
 done
 
 if [ $test_in_progress -eq 1 ]; then
-	echo "Good-bye!"
+  echo "Good-bye!"
 elif [ $auto_tor_grab -eq 0 ]; then # manual run
-	get_torrent_list
+  get_torrent_list
 
-	if [ $all_torrent -eq 1 ]; then
-		while IFS= read -r line; do
-			torrent_name_array+=("$line")
-		done < <(echo $torrent_list | $jq_executable --raw-output '.[] | .name')
+  if [ $all_torrent -eq 1 ]; then
+    while IFS= read -r line; do
+      torrent_name_array+=("$line")
+    done < <(echo $torrent_list | $jq_executable --raw-output '.[] | .name')
 
-		while IFS= read -r line; do
-			torrent_hash_array+=("$line")
-		done < <(echo $torrent_list | $jq_executable --raw-output '.[] | .hash')
-	else
-		for i in "${tor_arg_names[@]}"; do
-			torrent_name_list=$(echo "$torrent_list" | $jq_executable --raw-output --arg tosearch "$i" '.[] | select(.name|test("\($tosearch)";"i")) .name')
+    while IFS= read -r line; do
+      torrent_hash_array+=("$line")
+    done < <(echo $torrent_list | $jq_executable --raw-output '.[] | .hash')
+  else
+    for i in "${tor_arg_names[@]}"; do
+      torrent_name_list=$(echo "$torrent_list" | $jq_executable --raw-output --arg tosearch "$i" '.[] | select(.name|test("\($tosearch)";"i")) .name')
 
-			if [ -n "$torrent_name_list" ]; then # not empty
-				torrent_name_check=1
-				echo -e "\n\e[0;32;1mFor argument ### $i ###\e[0;32m"
-				echo -e "\e[0;32;1mI found the following torrent:\e[0;32m"
-				echo "$torrent_name_list"
-			else
-				torrent_name_check=0
-			fi
+      if [ -n "$torrent_name_list" ]; then # not empty
+        torrent_name_check=1
+        echo -e "\n\e[0;32;1mFor argument ### $i ###\e[0;32m"
+        echo -e "\e[0;32;1mI found the following torrent:\e[0;32m"
+        echo "$torrent_name_list"
+      else
+        torrent_name_check=0
+      fi
 
-			if [ $torrent_name_check -eq 0 ]; then
-				echo -e "\e[0;31;1mI didn't find a torrent with the text: \e[21m$1\e[0m"
-				shift
-				continue
-			else
-				while read -r single_found; do
-					torrent_name_array+=("$single_found")
-					hash=$(echo "$torrent_list" | $jq_executable --raw-output --arg tosearch "$single_found" '.[] | select(.name == "\($tosearch)") | .hash')
-					torrent_hash_array+=("$hash")
-				done <<< "$torrent_name_list"
-			fi
-		done
-	fi
+      if [ $torrent_name_check -eq 0 ]; then
+        echo -e "\e[0;31;1mI didn't find a torrent with the text: \e[21m$1\e[0m"
+        shift
+        continue
+      else
+        while read -r single_found; do
+          torrent_name_array+=("$single_found")
+          hash=$(echo "$torrent_list" | $jq_executable --raw-output --arg tosearch "$single_found" '.[] | select(.name == "\($tosearch)") | .hash')
+          torrent_hash_array+=("$hash")
+        done <<< "$torrent_name_list"
+      fi
+    done
+  fi
 
-	if [ ${#torrent_name_array[@]} -gt 0 ]; then
-		echo ""
-		for i in "${!torrent_name_array[@]}"; do
-			echo -ne "\n\e[0;1;4;32mFor the Torrent: \e[0;4;32m"
-			echo "${torrent_name_array[$i]}"
+  if [ ${#torrent_name_array[@]} -gt 0 ]; then
+    echo ""
+    for i in "${!torrent_name_array[@]}"; do
+      echo -ne "\n\e[0;1;4;32mFor the Torrent: \e[0;4;32m"
+      echo "${torrent_name_array[$i]}"
 
-			if [[ $ignore_private == true ]] || [ $applytheforce -eq 1 ]; then # Inject anyway the trackers inside any torrent
-				if [ $applytheforce -eq 1 ]; then
-					echo -e "\e[0m\e[33mForce mode is active, injecting trackers anyway\e[0m"
-				else
-					echo -e "\e[0m\e[33mignore_private set to true, injecting trackers anyway\e[0m"
-				fi
-				generate_trackers_list
-				inject_trackers ${torrent_hash_array[$i]}
-			else
-				private_check=$($curl_executable --silent --fail --show-error --request GET "${qbt_host}:${qbt_port}/api/v2/torrents/trackers?hash=$(echo "$torrent_list" | $jq_executable --raw-output --arg tosearch "${torrent_name_array[$i]}" '.[] | select(.name == "\($tosearch)") | .hash')" | $jq_executable --raw-output '.[0] | .msg | contains("private")')
+      if [[ $ignore_private == true ]] || [ $applytheforce -eq 1 ]; then # Inject anyway the trackers inside any torrent
+        if [ $applytheforce -eq 1 ]; then
+          echo -e "\e[0m\e[33mForce mode is active, injecting trackers anyway\e[0m"
+        else
+          echo -e "\e[0m\e[33mignore_private set to true, injecting trackers anyway\e[0m"
+        fi
+        generate_trackers_list
+        inject_trackers ${torrent_hash_array[$i]}
+      else
+        private_check=$($curl_executable --silent --fail --show-error --request GET "${qbt_host}:${qbt_port}/api/v2/torrents/trackers?hash=$(echo "$torrent_list" | $jq_executable --raw-output --arg tosearch "${torrent_name_array[$i]}" '.[] | select(.name == "\($tosearch)") | .hash')" | $jq_executable --raw-output '.[0] | .msg | contains("private")')
 
-				if [[ $private_check == true ]]; then
-					private_tracker_name=$($curl_executable --silent --fail --show-error --request GET "${qbt_host}:${qbt_port}/api/v2/torrents/trackers?hash=$(echo "$torrent_list" | $jq_executable --raw-output --arg tosearch "${torrent_name_array[$i]}" '.[] | select(.name == "\($tosearch)") | .hash')" | $jq_executable --raw-output '.[3] | .url' | sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/')
-					echo -e "\e[31m< Private tracker found \e[0m\e[33m-> $private_tracker_name <- \e[0m\e[31mI'll not add any extra tracker >\e[0m"
-				else
-					echo -e "\e[0m\e[33mThe torrent is not private, injecting trackers\e[0m"
-					generate_trackers_list
-					inject_trackers ${torrent_hash_array[$i]}
-				fi
-			fi
-		done
-	else
-		echo "No torrents found, exiting"
-	fi
+        if [[ $private_check == true ]]; then
+          private_tracker_name=$($curl_executable --silent --fail --show-error --request GET "${qbt_host}:${qbt_port}/api/v2/torrents/trackers?hash=$(echo "$torrent_list" | $jq_executable --raw-output --arg tosearch "${torrent_name_array[$i]}" '.[] | select(.name == "\($tosearch)") | .hash')" | $jq_executable --raw-output '.[3] | .url' | sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/')
+          echo -e "\e[31m< Private tracker found \e[0m\e[33m-> $private_tracker_name <- \e[0m\e[31mI'll not add any extra tracker >\e[0m"
+        else
+          echo -e "\e[0m\e[33mThe torrent is not private, injecting trackers\e[0m"
+          generate_trackers_list
+          inject_trackers ${torrent_hash_array[$i]}
+        fi
+      fi
+    done
+  else
+    echo "No torrents found, exiting"
+  fi
 else # auto_tor_grab active, so some *Arr
-	wait 5
-	get_torrent_list
+  wait 5
+  get_torrent_list
 
-	private_check=$($curl_executable --silent --fail --show-error --request GET "${qbt_host}:${qbt_port}/api/v2/torrents/trackers?hash=$hash" | $jq_executable --raw-output '.[0] | .msg | contains("private")')
+  private_check=$($curl_executable --silent --fail --show-error --request GET "${qbt_host}:${qbt_port}/api/v2/torrents/trackers?hash=$hash" | $jq_executable --raw-output '.[0] | .msg | contains("private")')
 
-	if [[ $private_check == true ]]; then
-		private_tracker_name=$($curl_executable --silent --fail --show-error --request GET "${qbt_host}:${qbt_port}/api/v2/torrents/trackers?hash=$hash" | $jq_executable --raw-output '.[3] | .url' | sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/')
-		echo -e "\e[31m< Private tracker found \e[0m\e[33m-> $private_tracker_name <- \e[0m\e[31mnot adding any trackers >\e[0m"
-	else
-		echo -e "\e[0m\e[33mThe torrent is not private, injecting trackers\e[0m"
-		generate_trackers_list
-		inject_trackers $hash
-	fi
+  if [[ $private_check == true ]]; then
+    private_tracker_name=$($curl_executable --silent --fail --show-error --request GET "${qbt_host}:${qbt_port}/api/v2/torrents/trackers?hash=$hash" | $jq_executable --raw-output '.[3] | .url' | sed -e 's/[^/]*\/\/\([^@]*@\)\?\([^:/]*\).*/\2/')
+    echo -e "\e[31m< Private tracker found \e[0m\e[33m-> $private_tracker_name <- \e[0m\e[31mnot adding any trackers >\e[0m"
+  else
+    echo -e "\e[0m\e[33mThe torrent is not private, injecting trackers\e[0m"
+    generate_trackers_list
+    inject_trackers $hash
+  fi
 fi
