[andrew_nt@DahliaEndeavor] Automatic backup of tracked files

diff --git a/bin/cron/backup_configs b/bin/cron/backup_configs
--- a/bin/cron/backup_configs
+++ b/bin/cron/backup_configs
@@ -2,6 +2,20 @@
 #
 # Backs up all files tracked by the git repository CONFIGS_HOME by commiting and
 # pushing it to the repository.
+
+TIMEOUT=60
+while ! nc -zw1 github.com 443; do
+  if [[ "$TIMEOUT" -eq 60 ]]; then
+    echo "Waiting for github connection."
+  fi
+  sleep 1
+  TIMEOUT=$((TIMEOUT - 1))
+  if [[ "$TIMEOUT" -lt 1 ]]; then
+    echo "Failed to establish a connection to github.com."
+    exit 1
+  fi
+done
+
 FROM="$(whoami)@$(hostname)"
 GIT_CONF="git --git-dir=\"${CONFIGS_GIT_DIR:-\"$HOME/.cfg\"}\" --work-tree=\"$HOME\""
 
